accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('', views.sign_in, name='sign_in'),
    path('sign_out/', views.sign_out, name='sign_out'),
    path('register/', views.register, name='register'),
]

software_architect_aide/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [path('admin/', admin.site.urls), path('dashboard/', views.dashboard, name='dashboard'),
               path('dashboard/architecture/create/upload/', views.create_upload, name='create_upload'),
               path('dashboard/architecture/create/reference/', views.create_reference, name='create_reference'),
               path('dashboard/architecture/create/manual/', views.create_manual, name='create_manual'),
               path('dashboard/architecture/delete/<int:architecture_id>', views.architecture_delete,
                    name='architecture_delete'),
               path('dashboard/architecture/export/<int:architecture_id>', views.architecture_export,
                    name='architecture_export'),
               path('dashboard/tradeoff/', views.tradeoff, name='tradeoff'),
               path('dashboard/evolution/', views.evolution, name='evolution'),
               path('dashboard/ontospy_report/', views.ontospy_report, name='ontospy_report'),
               path('dashboard/report/html_multi/<str:file_name>/', views.report_multi,
                    name='report-multi-index'),
               path('dashboard/report/html_multi/', views.report_multi_index, name='report-multi_index'),
               path('dashboard/report/<str:report_name>/', views.report, name='report'),
               path('dashboard/delete_all_architectures/', views.delete_all_architectures,
                    name='delete_all_architectures'),
               path('', include('accounts.urls', namespace='accounts')),
               ]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

software_architect_aide/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models import FileField


class Architecture(models.Model):
    name = models.CharField(max_length=30)
    owner = models.ForeignKey(User, related_name='architectures', on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)
    owl_file = FileField(upload_to='owl', unique=True)
    triple_count = models.IntegerField(default=0)
    creation_method = models.CharField(max_length=30, choices=(
        ('manual', 'ساخت دستی'), ('reference', 'براساس معماری مرجع'), ('evolution', 'تکامل معماری'),
        ('upload', 'بارگذاری هستان‌شناسی')))
    parent_architecture = models.ForeignKey('self', null=True, default=None, on_delete=models.SET_NULL)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=2, user-scalable=no"/>
    <meta name="description" content="سامانهٔ تصمیم‌یار معماری نرم‌افزار"/>
    <meta name="keywords" content="Data, Exporter"/>
    <meta name="theme-color" content="#ffffff"/>
    <title>سامانهٔ تصمیم‌یار معماری نرم‌افزار</title>
    <link rel="stylesheet" href="https://cdn.rtlcss.com/semantic-ui/2.4.1/semantic.rtl.min.css" integrity="sha384-yXUIpeQfH3cuk6u6Mwu8uyJXB2R3UOLvcha1343UCMA2TA7lQ14BFmrudI6LAP8A" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'software_architect_aide/css/style.css' %}"/>
    <link rel="shortcut icon" type="image/png" href="{% static 'software_architect_aide/logo.png' %}"/>
    {% block begin_css %}
    {% endblock %}
</head>
<body id="root">
{% block content %}
{% endblock %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdn.rtlcss.com/semantic-ui/2.4.1/semantic.min.js" integrity="sha384-6urqf2sgCGDfIXcoxTUOVIoQV+jFr/Zuc4O2wCRS6Rnd8w0OJ17C4Oo3PuXu8ZtF" crossorigin="anonymous"></script>
{% block end_js %}
{% endblock %}
</body>
</html>

templates/dashboard_analysis.html
{% extends 'base_dashboard.html' %}{% load static %}


{% block dashboard_content %}
    <div class="sixteen wide mobile thirteen wide tablet thirteen wide computer right floated column" id="content">
        <div class="ui padded grid">
            <div class="row">
                <h1 class="ui huge dividing header">معماری نرم‌افزار</h1>
            </div>

            <div class="row">
                <table class="ui celled padded selectable table">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>نام معماری</th>
                        <th>تعداد سه‌تایی‌ها</th>
                        <th>نحوهٔ ساخت</th>
                        <th>تاریخ ایجاد</th>
                        <th>فعالیت‌ها</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% if not architectures %}
                        <tr>
                            <th colspan="7">
                                هنوز هیچ معماری‌ای ایجاد نشده.
                            </th>
                        </tr>
                    {% endif %}
                    {% for architecture in architectures %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td>{{ architecture.name }}</td>
                            <td>{{ architecture.triple_count }}</td>
                            <td>{{ architecture.get_creation_method_display }}</td>
                            <td>{{ architecture.date_added }}</td>
                            <td>
                                <button class="ui icon button" onclick="open_modal({{ forloop.counter }}, 'visualize')">
                                    <i class="eye icon"></i>
                                </button>
                                <button class="ui icon button delete_item" onclick="open_modal({{ forloop.counter }}, 'delete')">
                                    <i class="trash icon"></i>
                                </button>
                                <button class="ui icon button" onclick="open_modal({{ forloop.counter }}, 'export')">
                                    <i class="download icon"></i>
                                </button>
                            </td>
                        </tr>

                        <div class="ui modal large visualize_{{ forloop.counter }}">
                            <i class="close icon"></i>
                            <div class="header">
                                نمایش تصویر هستان‌شناسی
                            </div>
                            <div class="image content">
                                <div class="ui fluid image">
                                    <img class="pan" src="/media/visual/{{ architecture.owl_file }}.png">
                                </div>
                            </div>
                            <div class="actions">
                                <a download="/media/visual/{{ architecture.owl_file }}.png" href="/media/visual/{{ architecture.owl_file }}.png">
                                    <div class="ui positive right labeled icon button">
                                        بارگیری <i class="download icon"></i>
                                    </div>
                                </a>
                            </div>
                        </div>

                        <div class="ui modal tiny delete_{{ forloop.counter }}">
                            <i class="close icon"></i>
                            <div class="header">
                                آیا مایل به حذف معماری هستید؟
                            </div>
                            <div class="image content">
                                <div class="description">
                                    <p>درصورت حذف معماری {{ architecture.name }} امکان بازیابی آن وجود ندارد.</p>
                                </div>
                            </div>
                            <div class="actions">
                                <form action="{% url 'architecture_delete' architecture_id=architecture.id %}" method="POST">
                                    <div class="ui black deny button">
                                        انصراف
                                    </div>
                                    {% csrf_token %}
                                    <button class="ui red danger right labeled icon button" type="submit">بله
                                        <i class="trash icon"></i></button>
                                </form>
                            </div>
                        </div>
                        {% include 'dashboard_export_modal.html'  with number=forloop.counter architecture=architecture %}
                    {% endfor %}
                    </tbody>
                    <tfoot class="full-width">
                    <tr>
                        <th colspan="7">
                            <form method="GET" action="{% url 'delete_all_architectures' %}">
                                <button id="tables_download_update" class="ui small red labeled icon button" type="submit">
                                    <i class="trash icon"></i> حذف همه
                                </button>
                            </form>
                        </th>
                    </tr>
                    </tfoot>
                </table>
            </div>
            <div class="ui hidden section divider"></div>
        </div>
    </div>
{% endblock %}

templates/dashboard_create_manual_field.html
<div class="ui field action input">
    <input type="text" name="{{ name }}[]" placeholder="{{ placeholder }}">
    <button class="ui red icon button delete_field">
        <i class="trash icon"></i>
    </button>
</div>

templates/dashboard_create_manual_field_comprises.html
<div class="two fields">
    <div class="field">
        <label> الگو:</label> <select name="comprises_pattern[]" class="ui fluid search selection dropdown">
        <option value="">الگو را انتخاب کنید.</option>
        {% for pattern in instances.patterns %}
            <option value="{{ pattern }}">{{ pattern }}</option>
        {% endfor %}
    </select>
    </div>
    <div class="ui bottom aligned centered grid">
        <div class="column">
            <label><a class="ui grey right pointing label">دربرگیرندهٔ است</a></label>
        </div>
    </div>
    <div class="field">
        <label> راهکنش:</label> <select name="comprises_tactic[]" class="ui fluid search selection dropdown">
        <option value="">راهکنش را انتخاب کنید.</option>
        {% for tactic in instances.tactics %}
            <option value="{{ tactic }}">{{ tactic }}</option>
        {% endfor %}
    </select>
    </div>
    <div class="ui bottom aligned centered grid">
        <div class="column">
            <button class="ui red icon button delete_field_two">
                <i class="trash icon"></i>
            </button>
        </div>
    </div>
</div>

templates/dashboard_create_manual_field_is_achieved_by.html
<div class="two fields">
    <div class="field">
        <label> دغدغه:</label> <select name="is_achieved_by_concern[]" class="ui fluid search selection dropdown">
        <option value="">یک مخاطره، نیازمندی حرفه یا ویژگی کیفی را انتخاب کنید.</option>
        {% for concern in instances.concerns %}
            <option value="{{ concern }}">{{ concern }}</option>
        {% endfor %}
    </select>
    </div>
    <div class="ui bottom aligned centered grid">
        <div class="column">
            <label><a class="ui grey right pointing label">نائل می‌شود توسطِ</a></label>
        </div>
    </div>
    <div class="field">
        <label> راهکنش:</label> <select name="is_achieved_by_tactic[]" class="ui fluid search selection dropdown">
        <option value="">راهکنش را انتخاب کنید.</option>
        {% for tactic in instances.tactics %}
            <option value="{{ tactic }}">{{ tactic }}</option>
        {% endfor %}
    </select>
    </div>
    <div class="ui bottom aligned centered grid">
        <div class="column">
            <button class="ui red icon button delete_field_two">
                <i class="trash icon"></i>
            </button>
        </div>
    </div>
</div>

templates/dashboard_home.html
{% extends 'base_dashboard.html' %}{% load static %}


{% block dashboard_content %}
    <div class="sixteen wide mobile thirteen wide tablet thirteen wide computer right floated column" id="content">
        <div class="ui padded grid">
            <div class="row">
                <h1 class="ui huge dividing header">معماری نرم‌افزار</h1>
            </div>

            <div class="row">
                <table class="ui celled padded selectable table">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>نام معماری</th>
                        <th>تعداد سه‌تایی‌ها</th>
                        <th>نحوهٔ ساخت</th>
                        <th>تاریخ ایجاد</th>
                        <th>فعالیت‌ها</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% if not architectures %}
                        <tr>
                            <th colspan="7">
                                هنوز هیچ معماری‌ای ایجاد نشده.
                            </th>
                        </tr>
                    {% endif %}
                    {% for architecture in architectures %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td>{{ architecture.name }}</td>
                            <td>{{ architecture.triple_count }}</td>
                            <td>{{ architecture.get_creation_method_display }}</td>
                            <td>{{ architecture.date_added }}</td>
                            <td>
                                <button class="ui icon button" onclick="open_modal({{ forloop.counter }}, 'visualize')">
                                    <i class="eye icon"></i>
                                </button>
                                <button class="ui icon button delete_item" onclick="open_modal({{ forloop.counter }}, 'delete')">
                                    <i class="trash icon"></i>
                                </button>
                                <button class="ui icon button" onclick="open_modal({{ forloop.counter }}, 'export')">
                                    <i class="download icon"></i>
                                </button>
                                <a href="{% url 'tradeoff' %}?architecture_id={{ architecture.id }}">
                                    <button class="ui icon button">
                                        <i class="balance scale icon"></i>
                                    </button>
                                </a> <a href="{% url 'evolution' %}?architecture_id={{ architecture.id }}">
                                <button class="ui icon button">
                                    <i class="sync icon"></i>
                                </button>
                            </a>
                            </td>
                        </tr>

                        <div class="ui modal large visualize_{{ forloop.counter }}">
                            <i class="close icon"></i>
                            <div class="header">
                                نمایش تصویر هستان‌شناسی
                            </div>
                            <div class="image content">
                                <div class="ui fluid image">
                                    <img class="pan" alt="تصویر هستان‌شناسی" src="/media/visual/{{ architecture.owl_file }}.png">
                                </div>
                            </div>
                            <div class="actions">
                                <a download="/media/visual/{{ architecture.owl_file }}.png" href="/media/visual/{{ architecture.owl_file }}.png">
                                    <div class="ui positive right labeled icon button">
                                        بارگیری <i class="download icon"></i>
                                    </div>
                                </a>
                            </div>
                        </div>

                        <div class="ui modal tiny delete_{{ forloop.counter }}">
                            <i class="close icon"></i>
                            <div class="header">
                                آیا مایل به حذف معماری هستید؟
                            </div>
                            <div class="image content">
                                <div class="description">
                                    <p>درصورت حذف معماری {{ architecture.name }} امکان بازیابی آن وجود ندارد.</p>
                                </div>
                            </div>
                            <div class="actions">
                                <form action="{% url 'architecture_delete' architecture_id=architecture.id %}" method="POST">
                                    <div class="ui black deny button">
                                        انصراف
                                    </div>
                                    {% csrf_token %}
                                    <button class="ui red danger right labeled icon button" type="submit">بله
                                        <i class="trash icon"></i></button>
                                </form>
                            </div>
                        </div>
                        {% include 'dashboard_export_modal.html'  with number=forloop.counter architecture=architecture %}
                    {% endfor %}
                    </tbody>
                    <tfoot class="full-width">
                    <tr>
                        <th colspan="7">
                            <form method="GET" action="{% url 'delete_all_architectures' %}">
                                <button class="ui small red labeled icon button" type="submit">
                                    <i class="trash icon"></i> حذف همه
                                </button>
                            </form>
                        </th>
                    </tr>
                    </tfoot>
                </table>
            </div>
            <div class="ui hidden section divider"></div>
        </div>
    </div>
{% endblock %}

templates/dashboard_tradeoff.html
{% extends 'base_dashboard.html' %}{% load static %}


{% block dashboard_content %}
    <div class="sixteen wide mobile thirteen wide tablet thirteen wide computer right floated column" id="content">
        <div class="ui padded grid">
            <div class="row">
                <h1 class="ui huge dividing header">تحلیل بده‌بستان‌های معماری</h1>
            </div>
            <div class="blurring dimmable image">
                <div class="ui dimmer">
                    <div class="content">
                        <div class="center">
                            <div class="ui list">
                                <div class="item">
                                    <div class="header">نام معماری</div>
                                    {{ architecture.name }}
                                </div>
                                <div class="item">
                                    <div class="header">تعداد سه‌تایی‌ها</div>
                                    {{ architecture.triple_count }}
                                </div>
                                <div class="item">
                                    <div class="header">نحوهٔ ساخت</div>
                                    {{ architecture.get_creation_method_display }}
                                </div>
                                <div class="item">
                                    <div class="header">تاریخ ایجاد</div>
                                    {{ architecture.date_added }}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <img style="width: 100%;" alt="تصویر هستان‌شناسی" src="/media/visual/{{ architecture.owl_file }}.png">
            </div>
            <div class="ui hidden section divider"></div>
            <table class="ui celled padded selectable table">
                <thead>
                <tr>
                    <th>#</th>
                    <th>ویژگی کیفی اول</th>
                    <th>ویژگی کیفی دوم</th>
                    <th>روابط</th>
                </tr>
                </thead>
                <tbody>

                {% if not quality_relations %}
                    <tr>
                        <th colspan="4">
                            معماری انتخاب شده فاقد ویژگی کیفی است.
                        </th>
                    </tr>
                {% endif %}

                {% for qualities, relations in quality_relations.items %}
                    <tr>
                        <td>
                            {{ forloop.counter }}
                        </td>
                        {% for quality in qualities %}
                            <td>
                                {{ quality }}
                            </td>
                        {% endfor %}
                        <td>
                            {% for relation in relations %}
                                <div class="ui {{ relation.1 }} label">
                                    {{ relation.0 }}
                                </div>
                            {% endfor %}
                        </td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

templates/register.html
{% extends 'base.html' %}{% load static %}

{% block content %}
    <div class="ui middle aligned center aligned grid">
        <div class="column">
            <h2 class="ui teal center aligned header">
                <img class="image" src="{% static 'software_architect_aide/logo.png' %}"/> سامانهٔ تصمیم‌یار معماری
                نرم‌افزار </h2>
            <form class="ui large form" method="post" action="{% url 'accounts:register' %}">
                {% csrf_token %}
                <div class="ui stacked segment">
                    <div class="field">
                        <div class="ui left icon input">
                            <i class="user icon"></i> <input name="email" placeholder="آدرس ایمیل" type="text"/>
                        </div>
                    </div>
                    <div class="field">
                        <div class="ui left icon input">
                            <i class="lock icon"></i> <input name="password" placeholder="رمز عبور" type="password"/>
                        </div>
                    </div>
                    <div class="field">
                        <div class="ui left icon input">
                            <i class="lock icon"></i>
                            <input name="password2" placeholder="تکرار رمز عبور" type="password"/>
                        </div>
                    </div>

                    <div class="field">
                        <div class="g-recaptcha" data-sitekey="6LfYbLUZAAAAACC9Q4oHlcv0W45ybdpZVIJXnyjd"></div>
                    </div>
                    <div class="ui fluid large teal submit button">ثبت نام</div>
                </div>
                {% if  duplicate_user %}
                    <div class="ui negative message">
                        <i class="close icon"></i>
                        <ul class="list">
                            <li>این کاربر قبلا در سیستم ثبت نام شده است.</li>
                        </ul>
                    </div>
                {% endif %}
                {% if not true_captcha %}
                    <div class="ui negative message">
                        <i class="close icon"></i>
                        <ul class="list">
                            <li>لطفا تیک من ربات نیستم را بزنید.</li>
                        </ul>
                    </div>
                {% endif %}
                {% if not_match_password %}
                    <div class="ui negative message">
                        <i class="close icon"></i>
                        <ul class="list">
                            <li>پسورد ها با یکدیگر برابر نیستند.</li>
                        </ul>
                    </div>
                {% endif %}
                <div class="ui error message"></div>
            </form>
            <div class="ui message">حساب کاربری دارید؟ <a href="{% url "accounts:sign_in" %}">ورود</a></div>
        </div>
    </div>
{% endblock %}

{% block begin_css %}
    <style type="text/css">
        body {
            background-color: #dadada;
            -webkit-font-smoothing: antialiased;
            -moz-font-smoothing: grayscale;
        }

        body > .ui.grid {
            height: 100%;
        }

        .column {
            max-width: 450px;
        }
    </style>
{% endblock %}

{% block end_js %}
    <script>
        $(document).ready(function () {
            $(".ui.form").form({
                fields: {
                    email: {
                        identifier: "email",
                        rules: [
                            {
                                type: "empty",
                                prompt: "لطفا نشانی ایمیلتان را وارد کنید."
                            },
                            {
                                type: "email",
                                prompt: "لطفا ایمیل صحیح وارد کنید."
                            }
                        ]
                    },
                    password: {
                        identifier: "password",
                        rules: [
                            {
                                type: "empty",
                                prompt: "لطفا رمز عبور را وارد کنید."
                            },
                            {
                                type: "length[6]",
                                prompt: "طول رمز عبور حداقل باید شش حرف باشد."
                            }
                        ]
                    }
                }
            });
        });

        $('.message .close')
            .on('click', function () {
                $(this)
                    .closest('.message')
                    .transition('fade')
                ;
            })
        ;
    </script>
    <script src='https://www.google.com/recaptcha/api.js'></script>
{% endblock %}

templates/sign_in.html
{% extends 'base.html' %}{% load static %}

{% block content %}
    <div class="ui middle aligned center aligned grid">
        <div class="column">
            <h2 class="ui teal center aligned header">
                <img class="image" src="{% static 'software_architect_aide/logo.png' %}"/> سامانهٔ تصمیم‌یار معماری
                نرم‌افزار </h2>
            <form class="ui large form" method="post" action="{% url "accounts:sign_in" %}">
                {% csrf_token %}
                <div class="ui stacked segment">
                    <div class="field">
                        <div class="ui left icon input">
                            <i class="user icon"></i> <input name="email" placeholder="آدرس ایمیل" type="text"/>
                        </div>
                    </div>
                    <div class="field">
                        <div class="ui left icon input">
                            <i class="lock icon"></i> <input name="password" placeholder="رمز عبور" type="password"/>
                        </div>
                    </div>

                    <div class="ui fluid large teal submit button">ورود</div>
                </div>
                {% if not success %}
                    <div class="ui negative message">
                        <i class="close icon"></i>
                        <ul class="list">
                            <li>نام کاربری یا رمز عبور را اشتباه وارد کردید.</li>
                        </ul>
                    </div>
                {% endif %}
                {% if register_success %}
                    <div class="ui positive message">
                        <i class="close icon"></i>
                        <ul class="list">
                            <li>ثبت‌نام شما با موفقیت انجام پذیرفت.</li>
                        </ul>
                    </div>
                {% endif %}
                <div class="ui error message"></div>
            </form>
            <div class="ui message">حساب کاربری ندارید؟<a href="{% url 'accounts:register' %}"> ثبت‌نام</a></div>
        </div>
    </div>
{% endblock %}

{% block begin_css %}
    <style type="text/css">
        body {
            background-color: #dadada;
            -webkit-font-smoothing: antialiased;
            -moz-font-smoothing: grayscale;
        }

        body > .ui.grid {
            height: 100%;
        }

        .column {
            max-width: 450px;
        }
    </style>
{% endblock %}

{% block end_js %}
    <script>
        $(document).ready(function () {
            $(".ui.form").form({
                fields: {
                    email: {
                        identifier: "email",
                        rules: [
                            {
                                type: "empty",
                                prompt: "لطفا نشانی ایمیلتان را وارد کنید."
                            },
                            {
                                type: "email",
                                prompt: "لطفا ایمیل صحیح وارد کنید."
                            }
                        ]
                    },
                    password: {
                        identifier: "password",
                        rules: [
                            {
                                type: "empty",
                                prompt: "لطفا رمز عبور را وارد کنید."
                            },
                            {
                                type: "length[6]",
                                prompt: "طول رمز عبور حداقل باید شش حرف باشد."
                            }
                        ]
                    }
                }
            });
        });

        $('.message .close')
            .on('click', function () {
                $(this)
                    .closest('.message')
                    .transition('fade')
                ;
            })
        ;
    </script>
{% endblock %}